In [1]:
# First import PyTorch
import torch

In [2]:
def activation(x):
    """
    Sigmoid activation function
    
    Arguments:
    ----------
    x: torch.Tensor
    """
    return 1/(1 + torch.exp(-x))

# Tensors, for a Layer

In [3]:
### Generate some data

# Set the random seed, so things are predictable
torch.manual_seed(7)

# Features are 5 random normal variables
features = torch.randn((1, 5))

# True weights for our data,
# random normal variables again
weigths = torch.randn_like(features)
# and a true bias term
bias = torch.rand((1, 1))

In [4]:
## Calculate the output of this network using
## the weights and bias tensors
output = activation(torch.sum(features * weigths) \
                    + bias)

In [5]:
## Calculate the output of this network using
## the matrix multiplication
output = activation(
        torch.mm(features, weigths.view(5, 1)) + bias)

# Stack Them up - Multiple Layers

In [6]:
### Generate some data

# Set seed
torch.manual_seed(7)

features = torch.randn((1, 3))

# Define the size of each layer in our network
# No of input units, must match no of input features
n_input = features.shape[1]
n_hidden = 2
n_output = 1

# Weights for inputs  to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

Calculate the output for this multi-layer network.

In [7]:
hidden_output = activation(torch.mm( features, W1) + B1)

output = activation( torch.mm(hidden_output, W2) + B2)

print(output)

tensor([[0.3171]])


# Numpy to Torch an back

PyTorch has a great feature for converting between Numpy arrays and Torch tensors.

In [8]:
import numpy as np
a = np.random.rand(4,3)
a

array([[ 0.57450009,  0.33133188,  0.04505586],
       [ 0.3955184 ,  0.61071548,  0.72011295],
       [ 0.24232632,  0.10158064,  0.46696603],
       [ 0.51651322,  0.7029241 ,  0.56321523]])

In [9]:
b = torch.from_numpy(a)
b

tensor([[0.5745, 0.3313, 0.0451],
        [0.3955, 0.6107, 0.7201],
        [0.2423, 0.1016, 0.4670],
        [0.5165, 0.7029, 0.5632]], dtype=torch.float64)

In [10]:
b.numpy()

array([[ 0.57450009,  0.33133188,  0.04505586],
       [ 0.3955184 ,  0.61071548,  0.72011295],
       [ 0.24232632,  0.10158064,  0.46696603],
       [ 0.51651322,  0.7029241 ,  0.56321523]])

The memory is shared between the Numpy array and Torch tensor, so if we change the values **in-place** of one object, the other will change as well.

In [11]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[1.1490, 0.6627, 0.0901],
        [0.7910, 1.2214, 1.4402],
        [0.4847, 0.2032, 0.9339],
        [1.0330, 1.4058, 1.1264]], dtype=torch.float64)

In [12]:
# Numpy array matches new values from Tensor
a

array([[ 1.14900017,  0.66266375,  0.09011172],
       [ 0.7910368 ,  1.22143096,  1.4402259 ],
       [ 0.48465264,  0.20316128,  0.93393206],
       [ 1.03302644,  1.40584821,  1.12643047]])